# Generated by Django 5.0.7 on 2024-07-18 18:00

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contact_phone_number_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(max_length=10, validators=[contacts.models.validate_phone_number]),
        ),
    ]
